apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: compute-svc-alerts
spec:
  groups:
  - name: compute-svc-rules
    rules:
    - alert: HighLatency
      expr: histogram_quantile(0.95, sum(rate(http_request_latency_seconds_bucket[5m])) by (le)) > 0.5
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "High p95 Latency on {{ $labels.instance }}"
        description: "Latency is above 0.5s for more than 5 minutes."
     

    - alert: HighErrorRate
      expr: sum(rate(http_requests_total{status!~"2.*"}[5m])) / sum(rate(http_requests_total[5m])) > 0.01
      for: 5m
      labels:
        severity: critical
      annotations:
        summary: "High error rate on {{ $labels.instance }}"
        description: "More than 1% of requests are failing for over 5 minutes."
